### ISSUE TITLE
Roadmap - big boom update

### ISSUE THREAD

**Issue by f3l1x** [nette/docs#533]
Hi.

I'm going to focus on documentation and improvements in next following weeks/months. I'll try to solve all related issues. Document all new stuff, remove all deprecated stuff and many other things.

You known I have my own job as many others here, so I can't set up deadlines, but I can set up roadmap. 

I gladly see you join me on my journey.

-----

![](https://i.imgflip.com/1rilzl.jpg)

-----

# Roadmap

## ~~Warm up~~

- [x] #46 (`quickstart - no presenter mapping in config`)
- [x] #44 (`Add generator command for building whole site at once`) 

## Quick Start & Bootstrap [[filter](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+QuickStart%22)]

- [x] Create quickstart branch for Nette 2.3
- [x] Synchronize quickstart for Nette 2.3
- [x] #217 (`Bootstrap: removed Configurator::DEVELOPMENT & PRODUCTION`)
- [x] #219 (`Bootstrap: zdokumentovat Configurator::addServices()`)

## Tracy [[filter](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+Tracy%22)]

- [x] #201 (`Tracy: detekce vývojového řežimu na základě cookies`)
- [ ] #205 (`Tracy: přizpůsobení dumpování objektů`)
- [x] #208 (`Tracy: tvorba vlastního loggeru`)
- [x] #240 (`Debugging: document switching on via $configurator and Tracy, fix info about E_NOTICE/E_WARNING`)

## MVC/Application/Routing [[filter1](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+MVP%22)] [[filter2](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+Application%22)]

- [x] #203 (`Application: all presenters are created in Dependency Injection container`)
- [x] #390 (`Presentery: ukonceni behu`) (Thanks @JanGalek #606)
- [x] #322 (`Add documentation of Nette\Application\UI\Multiplier`)
- [x] #238 (`Components: add use-case of a real component, clarify advanced use of components`)
- [x] #204 (`Application: LinkGenerator + {link} macro without presenter`)
- [x] #211 (`Application: removed case insensitivity for presenters and actions`)
- [x] #215 (`Application: Router caching + action name can begin with number`)
- [x] #81 (`Translate routing improvements from English to Czech`)
- [x] #239 (`Routing: remove deprecated stuff, path mask, fix simple router and document new features`)

## Dependency Injection [[filter](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+Dependency-Injection%22)]

> @f3l1x handle all issues

- [x] #528 (`DI - remove deprecated extending service`)
- [x] #230 (`DI: zdokumentovat dynamic services`)
- [x] #386 (`Configuring: better description for DI`)
- [x] #222 (`DI: service aliases`)
- [x] #224 (`DI: zdokumentovat DecoratorExtension, DIExtension a InjectExtension`)
- [x] #226 (`DI: zdokumentovat CompilerExtension::validateConfig()`)
- [x] #228 (`DI: zdokumentovat chained syntax`)
- [x] #231 (`DI: zdokumentovat parametry pro extensions v ExtensionsExtension`)
- [x] #493 (`DI: document autowiring options (no, self, interface)`)

## Latte [[filter](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+Latte%22)]

- [x] #245 (`Latte: Přidat upozornění na includeblock na možné xss`)

## Cache [[filter](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+Cache%22)]

- [x] #374 (`Přidat soupis úložišť pro cache`)

## Utils [[filter](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+Utils%22)]

- [x] #555 (`Json - add information about sendResponse(new JsonResponse)`)
- [x] #496 (`Utils: add page about DateTime`)
- [x] #595 (`SafeStream - enhancement`)
- [x] #602 (`Callback - create new page`)
- [x] #603 (`ArrayHash - create docs`)
- [x] #604 (`ArrayList - create docs`)
- [x] #242 (`Paging: overhaul, add use-cases`)

## Database [[filter](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+Database%22)]

- [x] #216 (`Database: nové operátory a značky`)

## HTTP [[filter](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+HTTP%22)]

- [x] #550 (`HTTP: document CSP support & nonce`)

## PhpGenerator [[filter](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+PhpGenerator%22)]

- [x] #586 (`PhpGenerator - document this package`)

## Mail [[filter](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+Mail%22)]

- [x] #478 (`Mail: document FallbackMailer`)

## Ajax [[filter](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+Ajax%22)]

- [ ] #241 (`Ajax: overhaul`)

## Maintenance [[filter](https://github.com/nette/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Type%3A+Maintenance%22)]

- [x] #223  (`Nova stranka migrace nette 2.2 -> 2.3`)
- [x] #487 (`Main migration page`)
- [x] #394 (`Opening editor url handler under gnome (ubuntu)`)

**Comment by dg** [comment]
Thank you, it is awesome!!!

**Comment by premekkoch** [comment]
@f3l1x Will you mentor me, if I join?

**Comment by f3l1x** [comment]
Sure, happy to see you buddy. It will be long-loong journey ;-)

**Comment by revager29** [comment]
I would like to help if my knowledge is enough :)

**Comment by f3l1x** [comment]
@revager29 You're welcome. Join us at our journey!

**Comment by f3l1x** [comment]
## Status update 26.6.2017

Yesterday I have prepared a lot of PR's to synchronize QuickStart and many other typos.

PR:
- #531 
- #534 
- #536 
- #537 
- #538 
- #539 
- #540 
- #541 
- #542 
- #543 (pending) [:hourglass:]
- #532 (pending) [:hourglass:]

## Status update 27.6.2017

Today a few more PR's has to come up.

PR:
- #545 (pending) [:hourglass:]
- #544 (pending) [:hourglass:]

Bigger thing, I've labeled all open issues to propel `Area` (Mail, Tracy, Latte, etc..) and closed some outdated/not-relevant issues.

The whole list of all label is here: https://github.com/nette/docs/labels

**Comment by f3l1x** [comment]
## Status update 29.6.2017

Today's good day. All tickets (2) there were in plan in June are solved. Good job guys.!

I'm just collecting all data for next month. QuickStart.

**Comment by f3l1x** [comment]
## Status update 03.07.2017

Hello guys, I have been overwhelmed a couple days ago, cause I was moving into the new house.

A few things to this month:

- [ ] prepare quick start for Nette 2.3 (Personally I think it's gonna be fast & furious. Not any special things, just create branch and synchronize all necessary stuff). **Who want to do that?**

- [ ] resolve some bootstrap issues
    - [ ] #217 (`Bootstrap: removed Configurator::DEVELOPMENT & PRODUCTION`)
    - [ ] #219 (`Bootstrap: zdokumentovat Configurator::addServices()`)

-----

What do you think guys @revager29 and @premekkoch, wanna do that? :-)

**Comment by dg** [comment]
I pushed quickstart v2.3 https://github.com/nette/tutorial-quickstart/tree/v2.3. The problem is that tutorial is written for old version of sandbox without SignFormFactories. So it is needed to fix chapter about authorization.

**Comment by f3l1x** [comment]
@dg Thanks. We'll take care about it. :-)

**Comment by dg** [comment]
The question is, whether it really make sense to invest energy into the quickstart for 2.3. Isn't it better to simply delete it and link to 2.4?

**Comment by f3l1x** [comment]
@dg I think it is, I handle it, it scares me in my dreams. :-D

**Comment by f3l1x** [comment]
# Status update 17.07.2017

It has been an one hell of the weekend. I've finally moved in, I've finally internet connection, so I am alive again. 

We solved a few tickets during these days:

- https://github.com/nette/docs/issues/244
- https://github.com/nette/docs/issues/225
- https://github.com/nette/docs/issues/260
- https://github.com/nette/docs/issues/217
- https://github.com/nette/docs/issues/377
- https://github.com/nette/docs/issues/243
- https://github.com/nette/docs/issues/203
- https://github.com/nette/docs/issues/322
- https://github.com/nette/docs/issues/210
- https://github.com/nette/docs/issues/221

Thank you all guys. 👍

**Comment by f3l1x** [comment]
# Status update 23.07.2017

We've made a huge homepage refactoring.

![dfqdzs9xuaaavyv](https://user-images.githubusercontent.com/538058/28502961-8b437966-6ffd-11e7-97ff-6046c060b430.jpg)

**Comment by JanGalek** [comment]
- [x] https://github.com/nette/docs/issues/390 (Presentery: ukonceni behu) - PR: https://github.com/nette/docs/pull/606

**Comment by f3l1x** [comment]
# Status update 25.07.2017

We're going much faster then I expected. :tada: I've reschedule all tickets from month-plan to package-plan.

**Comment by f3l1x** [comment]
# Status update 2.8.2017

@premekkoch (with little help of @dg) solved: #603, #604.
@JanGalek solved #478.

Thank you guys!

-----

At this time I'm working on Dependency Injection improvements, stay tuned. :-)

**Comment by f3l1x** [comment]
# Status update 15.8.2017 

@premekkoch  solved: #623 
@JanGalek  solved: #626, #622, #621
@f3l1x solved: #626 
Typos: @radekdostal (#627) @hermajan (#629)

Thank you guys!

------

We're still working on more issues to complete the docs. Please open new issues for things we forgot.

**Comment by f3l1x** [comment]
# Status update 6.9.2017

We've resolved many issues.

Issues: #231, #224, #226, #228, #602, #222, #586, #635 
PR: #643, #644, #645, #626, #633, #634 

---

Thank you guys!

**Comment by f3l1x** [comment]
# Status update 9.11.2017

It has been a while when we close the last issue. At this moment I focus on my 👨‍🏭  & 💰 . Don't be worry, I will fix all issues at the end. ;-)

🎉

**Comment by f3l1x** [comment]
# Status update 11.02.2018

We've resolved some small issues: 674, 663, 637, 668, 667, 669. Some of them weren't in this big list.

We're still keep going.

**Comment by f3l1x** [comment]
# Status update 9.9.2019

We've Nette 3.0, yay, 🎉. You can find tiny typos or deprecated stuff out there, but don't worry, we're working on that.

PR's: #775 #736

**Comment by f3l1x** [comment]
## Status update 28.10.2020

We've improved (well, @dg by itself these days) very well. Nette 3.0 has awesome doc!

Let's continue with the hard work.
